### ISSUE TITLE
Bug : panel audio plante lors de la sauvegarde

### ISSUE THREAD

**Issue by substring** [DjLeChuck/recalbox-manager#16]
Le message d'erreur : 
```
amixer: Unable to find simple control 'Master',0


  Error: Command failed: /recalbox/scripts/recalbox-config.sh volume undefined
  amixer: Unable to find simple control 'Master',0
  
  
      at checkExecSyncError (child_process.js:483:13)
      at Object.execSync (child_process.js:523:13)
      at Object.save (/usr/recalbox-manager2/controllers/audio.js:29:30)
      at next (native)
      at Object.<anonymous> (/usr/recalbox-manager2/node_modules/koa-route/index.js:34:19)
      at next (native)
      at Object.<anonymous> (/usr/recalbox-manager2/node_modules/koa-route/index.js:27:49)
      at next (native)
      at Object.<anonymous> (/usr/recalbox-manager2/node_modules/koa-route/index.js:27:49)
      at next (native)
```

**Comment by DjLeChuck** [comment]
Problème de la valeur `undefined` envoyée corrigé. Mais cela n'enlève pas le problème qui vient de votre script `/recalbox/scripts/recalbox-config.sh`

**Comment by DjLeChuck** [comment]
Je clos car c'est confirmé ce n'est pas lié au manager.
