### ISSUE TITLE
Impossible de compiler

### ISSUE THREAD

**Issue by substring** [DjLeChuck/recalbox-manager#41]
Depuis 3 semaines, impossible de compiler le manager:
```
Failed to compile.

Module not found: Error: Cannot resolve module 'jquery' in /home/subs/recalbox-buildroot-rpi3/output/build/recalbox-manager2-v2.0-beta/client/node_modules/react-select2-wrapper/lib/components


npm ERR! Linux 4.4.0-43-Microsoft
npm ERR! argv "/home/subs/recalbox-buildroot-rpi3/output/host/usr/bin/node" "/home/subs/recalbox-buildroot-rpi3/output/host/usr/bin/npm" "run" "build"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! client@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the client@0.1.0 build script 'react-scripts build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     react-scripts build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs client
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls client
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/subs/recalbox-buildroot-rpi3/output/build/recalbox-manager2-v2.0-beta/client/npm-debug.log

npm ERR! Linux 4.4.0-43-Microsoft
npm ERR! argv "/home/subs/recalbox-buildroot-rpi3/output/host/usr/bin/node" "/home/subs/recalbox-buildroot-rpi3/output/host/usr/bin/npm" "--prefix" "/home/subs/recalbox-buildroot-rpi3/output/build/recalbox-manager2-v2.0-beta" "run" "buildboth"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! express-server@0.0.1 buildboth: `npm run build && cd client && npm run build && cd ..`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the express-server@0.0.1 buildboth script 'npm run build && cd client && npm run build && cd ..'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the express-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build && cd client && npm run build && cd ..
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs express-server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls express-server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/subs/recalbox-buildroot-rpi3/npm-debug.log
```

le npm-debug.log dit :
```
0 info it worked if it ends with ok
1 verbose cli [ '/home/subs/recalbox-buildroot-rpi3/output/host/usr/bin/node',
1 verbose cli   '/home/subs/recalbox-buildroot-rpi3/output/host/usr/bin/npm',
1 verbose cli   '--prefix',
1 verbose cli   '/home/subs/recalbox-buildroot-rpi3/output/build/recalbox-manager2-v2.0-beta',
1 verbose cli   'run',
1 verbose cli   'buildboth' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 verbose run-script [ 'prebuildboth', 'buildboth', 'postbuildboth' ]
5 info lifecycle express-server@0.0.1~prebuildboth: express-server@0.0.1
6 silly lifecycle express-server@0.0.1~prebuildboth: no script for prebuildboth, continuing
7 info lifecycle express-server@0.0.1~buildboth: express-server@0.0.1
8 verbose lifecycle express-server@0.0.1~buildboth: unsafe-perm in lifecycle true
9 verbose lifecycle express-server@0.0.1~buildboth: PATH: /home/subs/recalbox-buildroot-rpi3/output/host/usr/lib/node_modules/npm/bin/node-gyp-bin:/home/subs/recalbox-buildroot-rpi3/output/build/recalbox-manager2-v2.0-beta/node_modules/.bin:/home/subs/recalbox-buildroot-rpi3/output/host/bin:/home/subs/recalbox-buildroot-rpi3/output/host/sbin:/home/subs/recalbox-buildroot-rpi3/output/host/usr/bin:/home/subs/recalbox-buildroot-rpi3/output/host/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/ProgramData/Oracle/Java/javapath:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Users/WaH/AppData/Local/Microsoft/WindowsApps:/mnt/c/adb:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Users/WaH/AppData/Local/Microsoft/WindowsApps
10 verbose lifecycle express-server@0.0.1~buildboth: CWD: /home/subs/recalbox-buildroot-rpi3/output/build/recalbox-manager2-v2.0-beta
11 silly lifecycle express-server@0.0.1~buildboth: Args: [ '-c', 'npm run build && cd client && npm run build && cd ..' ]
12 silly lifecycle express-server@0.0.1~buildboth: Returned: code: 1  signal: null
13 info lifecycle express-server@0.0.1~buildboth: Failed to exec buildboth script
14 verbose stack Error: express-server@0.0.1 buildboth: `npm run build && cd client && npm run build && cd ..`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/home/subs/recalbox-buildroot-rpi3/output/host/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/subs/recalbox-buildroot-rpi3/output/host/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid express-server@0.0.1
16 verbose cwd /home/subs/recalbox-buildroot-rpi3
17 error Linux 4.4.0-43-Microsoft
18 error argv "/home/subs/recalbox-buildroot-rpi3/output/host/usr/bin/node" "/home/subs/recalbox-buildroot-rpi3/output/host/usr/bin/npm" "--prefix" "/home/subs/recalbox-buildroot-rpi3/output/build/recalbox-manager2-v2.0-beta" "run" "buildboth"
19 error node v6.9.1
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error express-server@0.0.1 buildboth: `npm run build && cd client && npm run build && cd ..`
22 error Exit status 1
23 error Failed at the express-server@0.0.1 buildboth script 'npm run build && cd client && npm run build && cd ..'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the express-server package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run build && cd client && npm run build && cd ..
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs express-server
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls express-server
23 error There is likely additional logging output above.
```

**Comment by DjLeChuck** [comment]
Hum bizarre, je crois avoir eu ce problème une fois en local puis plus après... Je vais devoir me pencher dessus sérieusement car c'est un peu la galère la façon dont est géré jQuery pour le moment, je vais essayer de faire ça mieux.

**Comment by substring** [comment]
Un bucheron chauve m'a suggéré que ça pourrait etre lié au semver ... Le truc c'est que ca builde bien sur ton Travis ! Ou un pb de version de npm ?

**Comment by substring** [comment]
meme ton Travis plante : https://travis-ci.org/DjLeChuck/recalbox-manager/jobs/220209998#L1695
Attention a la gestion des erreurs dans ton compile.sh ;)

**Comment by DjLeChuck** [comment]
Corrigé via b7c9560df223c019ebe2522ea0d4cf634103d224
