### ISSUE TITLE
Manager not compiling with NodeJS 8.9.1

### ISSUE THREAD

**Issue by substring** [DjLeChuck/recalbox-manager#64]
Here is the output :

```
PATH="/home/subs/git/recalbox-build/output/host/bin:/home/subs/git/recalbox-build/output/host/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin" AR="/home/subs/git/recalbox-build/output/host/bin/arm-buildroot-linux-gnueabihf-ar" AS="/home/subs/git/recalbox-build/output/host/bin/arm-buildroot-linux-gnueabihf-as" LD="/home/subs/git/recalbox-build/output/host/bin/arm-buildroot-linux-gnueabihf-ld" NM="/home/subs/git/recalbox-build/output/host/bin/arm-buildroot-linux-gnueabihf-nm" CC="/home/subs/git/recalbox-build/output/host/bin/arm-buildroot-linux-gnueabihf-gcc" GCC="/home/subs/git/recalbox-build/output/host/bin/arm-buildroot-linux-gnueabihf-gcc" CPP="/home/subs/git/recalbox-build/output/host/bin/arm-buildroot-linux-gnueabihf-cpp" CXX="/home/subs/git/recalbox-build/output/host/bin/arm-buildroot-linux-gnueabihf-g++" FC="/home/subs/git/recalbox-build/output/host/bin/arm-buildroot-linux-gnueabihf-gfortran" F77="/home/subs/git/recalbox-build/output/host/bin/arm-buildroot-linux-gnueabihf-gfortran" RANLIB="/home/subs/git/recalbox-build/output/host/bin/arm-buildroot-linux-gnueabihf-ranlib" READELF="/home/subs/git/recalbox-build/output/host/bin/arm-buildroot-linux-gnueabihf-readelf" STRIP="/home/subs/git/recalbox-build/output/host/bin/arm-buildroot-linux-gnueabihf-strip" OBJCOPY="/home/subs/git/recalbox-build/output/host/bin/arm-buildroot-linux-gnueabihf-objcopy" OBJDUMP="/home/subs/git/recalbox-build/output/host/bin/arm-buildroot-linux-gnueabihf-objdump" AR_FOR_BUILD="/usr/bin/ar" AS_FOR_BUILD="/usr/bin/as" CC_FOR_BUILD="/usr/bin/gcc" GCC_FOR_BUILD="/usr/bin/gcc" CXX_FOR_BUILD="/usr/bin/g++" LD_FOR_BUILD="/usr/bin/ld" CPPFLAGS_FOR_BUILD="-I/home/subs/git/recalbox-build/output/host/include" CFLAGS_FOR_BUILD="-O2 -I/home/subs/git/recalbox-build/output/host/include" CXXFLAGS_FOR_BUILD="-O2 -I/home/subs/git/recalbox-build/output/host/include" LDFLAGS_FOR_BUILD="-L/home/subs/git/recalbox-build/output/host/lib -Wl,-rpath,/home/subs/git/recalbox-build/output/host/lib" FCFLAGS_FOR_BUILD="" DEFAULT_ASSEMBLER="/home/subs/git/recalbox-build/output/host/bin/arm-buildroot-linux-gnueabihf-as" DEFAULT_LINKER="/home/subs/git/recalbox-build/output/host/bin/arm-buildroot-linux-gnueabihf-ld" CPPFLAGS="-D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64" CFLAGS="-D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -O3 " CXXFLAGS="-D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -O3 " LDFLAGS="" FCFLAGS=" -O3 " FFLAGS=" -O3 " PKG_CONFIG="/home/subs/git/recalbox-build/output/host/bin/pkg-config" STAGING_DIR="/home/subs/git/recalbox-build/output/host/arm-buildroot-linux-gnueabihf/sysroot" INTLTOOL_PERL=/usr/bin/perl LD="/home/subs/git/recalbox-build/output/host/bin/arm-buildroot-linux-gnueabihf-g++" npm_config_arch=arm npm_config_target_arch=arm npm_config_build_from_source=true npm_config_nodedir=/home/subs/git/recalbox-build/output/build/nodejs-8.9.1 /home/subs/git/recalbox-build/output/host/usr/bin/npm --prefix /home/subs/git/recalbox-build/output/build/recalbox-manager2-decb5ef4a4854a327059d0344cb9c98fceda2cd4 run installboth

> recalbox-manager@2.0.1 installboth /home/subs/git/recalbox-build/output/build/recalbox-manager2-decb5ef4a4854a327059d0344cb9c98fceda2cd4
> npm install && cd client && npm install && cd ..

npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 499 packages in 9.477s
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
npm WARN deprecated clone@1.0.2: XSS vulnerability fixed in v1.0.3
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated react-tools@0.13.3: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated

> microtime@2.1.3 install /home/subs/git/recalbox-build/output/build/recalbox-manager2-decb5ef4a4854a327059d0344cb9c98fceda2cd4/client/node_modules/microtime
> node-gyp rebuild

  CXX(target) Release/obj.target/microtime/src/microtime.o
  SOLINK_MODULE(target) Release/obj.target/microtime.node
  COPY Release/microtime.node

> react-bootstrap-select@0.14.0 postinstall /home/subs/git/recalbox-build/output/build/recalbox-manager2-decb5ef4a4854a327059d0344cb9c98fceda2cd4/client/node_modules/react-bootstrap-select
> jsx jsx/ dist/

built Module("Select")
["Select"]
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.0.14 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1170 packages in 31.553s


   ╭─────────────────────────────────────╮
   │                                     │
   │   Update available 5.5.1 → 5.6.0    │
   │     Run npm i -g npm to update      │
   │                                     │
   ╰─────────────────────────────────────╯

PATH="/home/subs/git/recalbox-build/output/host/bin:/home/subs/git/recalbox-build/output/host/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin" AR="/home/subs/git/recalbox-build/output/host/bin/arm-buildroot-linux-gnueabihf-ar" AS="/home/subs/git/recalbox-build/output/host/bin/arm-buildroot-linux-gnueabihf-as" LD="/home/subs/git/recalbox-build/output/host/bin/arm-buildroot-linux-gnueabihf-ld" NM="/home/subs/git/recalbox-build/output/host/bin/arm-buildroot-linux-gnueabihf-nm" CC="/home/subs/git/recalbox-build/output/host/bin/arm-buildroot-linux-gnueabihf-gcc" GCC="/home/subs/git/recalbox-build/output/host/bin/arm-buildroot-linux-gnueabihf-gcc" CPP="/home/subs/git/recalbox-build/output/host/bin/arm-buildroot-linux-gnueabihf-cpp" CXX="/home/subs/git/recalbox-build/output/host/bin/arm-buildroot-linux-gnueabihf-g++" FC="/home/subs/git/recalbox-build/output/host/bin/arm-buildroot-linux-gnueabihf-gfortran" F77="/home/subs/git/recalbox-build/output/host/bin/arm-buildroot-linux-gnueabihf-gfortran" RANLIB="/home/subs/git/recalbox-build/output/host/bin/arm-buildroot-linux-gnueabihf-ranlib" READELF="/home/subs/git/recalbox-build/output/host/bin/arm-buildroot-linux-gnueabihf-readelf" STRIP="/home/subs/git/recalbox-build/output/host/bin/arm-buildroot-linux-gnueabihf-strip" OBJCOPY="/home/subs/git/recalbox-build/output/host/bin/arm-buildroot-linux-gnueabihf-objcopy" OBJDUMP="/home/subs/git/recalbox-build/output/host/bin/arm-buildroot-linux-gnueabihf-objdump" AR_FOR_BUILD="/usr/bin/ar" AS_FOR_BUILD="/usr/bin/as" CC_FOR_BUILD="/usr/bin/gcc" GCC_FOR_BUILD="/usr/bin/gcc" CXX_FOR_BUILD="/usr/bin/g++" LD_FOR_BUILD="/usr/bin/ld" CPPFLAGS_FOR_BUILD="-I/home/subs/git/recalbox-build/output/host/include" CFLAGS_FOR_BUILD="-O2 -I/home/subs/git/recalbox-build/output/host/include" CXXFLAGS_FOR_BUILD="-O2 -I/home/subs/git/recalbox-build/output/host/include" LDFLAGS_FOR_BUILD="-L/home/subs/git/recalbox-build/output/host/lib -Wl,-rpath,/home/subs/git/recalbox-build/output/host/lib" FCFLAGS_FOR_BUILD="" DEFAULT_ASSEMBLER="/home/subs/git/recalbox-build/output/host/bin/arm-buildroot-linux-gnueabihf-as" DEFAULT_LINKER="/home/subs/git/recalbox-build/output/host/bin/arm-buildroot-linux-gnueabihf-ld" CPPFLAGS="-D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64" CFLAGS="-D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -O3 " CXXFLAGS="-D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -O3 " LDFLAGS="" FCFLAGS=" -O3 " FFLAGS=" -O3 " PKG_CONFIG="/home/subs/git/recalbox-build/output/host/bin/pkg-config" STAGING_DIR="/home/subs/git/recalbox-build/output/host/arm-buildroot-linux-gnueabihf/sysroot" INTLTOOL_PERL=/usr/bin/perl LD="/home/subs/git/recalbox-build/output/host/bin/arm-buildroot-linux-gnueabihf-g++" npm_config_arch=arm npm_config_target_arch=arm npm_config_build_from_source=true npm_config_nodedir=/home/subs/git/recalbox-build/output/build/nodejs-8.9.1 /home/subs/git/recalbox-build/output/host/usr/bin/npm --prefix /home/subs/git/recalbox-build/output/build/recalbox-manager2-decb5ef4a4854a327059d0344cb9c98fceda2cd4 run buildboth

> recalbox-manager@2.0.1 buildboth /home/subs/git/recalbox-build/output/build/recalbox-manager2-decb5ef4a4854a327059d0344cb9c98fceda2cd4
> npm run build && cd client && npm run build && cd ..


> recalbox-manager@2.0.1 build /home/subs/git/recalbox-build/output/build/recalbox-manager2-decb5ef4a4854a327059d0344cb9c98fceda2cd4
> babel src -d dist

src/lib/osutils.js -> dist/lib/osutils.js
src/lib/utils.js -> dist/lib/utils.js
src/routes/conf.js -> dist/routes/conf.js
src/routes/get.js -> dist/routes/get.js
src/routes/grep.js -> dist/routes/grep.js
src/routes/post.js -> dist/routes/post.js
src/routes/save.js -> dist/routes/save.js
src/routes/upload.js -> dist/routes/upload.js
src/server.js -> dist/server.js

> client@0.1.0 build /home/subs/git/recalbox-build/output/build/recalbox-manager2-decb5ef4a4854a327059d0344cb9c98fceda2cd4/client
> react-scripts build

Creating an optimized production build...
Failed to compile.

Module build failed: TypeError: Error while loading rule 'flowtype/require-valid-file-annotation': _lodash2.default.get is not a function
    at exports.default (/home/subs/git/recalbox-build/output/build/recalbox-manager2-decb5ef4a4854a327059d0344cb9c98fceda2cd4/client/node_modules/eslint-plugin-flowtype/dist/rules/requireValidFileAnnotation.js:38:41)
    at Object.keys.filter.forEach.key (/home/subs/git/recalbox-build/output/build/recalbox-manager2-decb5ef4a4854a327059d0344cb9c98fceda2cd4/client/node_modules/eslint/lib/eslint.js:869:27)
    at Array.forEach (<anonymous>)
    at EventEmitter.module.exports.api.verify (/home/subs/git/recalbox-build/output/build/recalbox-manager2-decb5ef4a4854a327059d0344cb9c98fceda2cd4/client/node_modules/eslint/lib/eslint.js:841:93)
    at processText (/home/subs/git/recalbox-build/output/build/recalbox-manager2-decb5ef4a4854a327059d0344cb9c98fceda2cd4/client/node_modules/eslint/lib/cli-engine.js:264:31)
    at CLIEngine.executeOnText (/home/subs/git/recalbox-build/output/build/recalbox-manager2-decb5ef4a4854a327059d0344cb9c98fceda2cd4/client/node_modules/eslint/lib/cli-engine.js:754:26)
    at lint (/home/subs/git/recalbox-build/output/build/recalbox-manager2-decb5ef4a4854a327059d0344cb9c98fceda2cd4/client/node_modules/eslint-loader/index.js:42:18)
    at Object.module.exports (/home/subs/git/recalbox-build/output/build/recalbox-manager2-decb5ef4a4854a327059d0344cb9c98fceda2cd4/client/node_modules/eslint-loader/index.js:178:3)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! client@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the client@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/subs/.npm/_logs/2017-12-21T18_22_25_854Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! recalbox-manager@2.0.1 buildboth: `npm run build && cd client && npm run build && cd ..`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the recalbox-manager@2.0.1 buildboth script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/subs/.npm/_logs/2017-12-21T18_22_25_979Z-debug.log
package/pkg-generic.mk:234 : la recette pour la cible « /home/subs/git/recalbox-build/output/build/recalbox-manager2-decb5ef4a4854a327059d0344cb9c98fceda2cd4/.stamp_built » a échouée
make[2]: *** [/home/subs/git/recalbox-build/output/build/recalbox-manager2-decb5ef4a4854a327059d0344cb9c98fceda2cd4/.stamp_built] Erreur 1
Makefile:79 : la recette pour la cible « _all » a échouée
make[1]: *** [_all] Erreur 2
make[1] : on quitte le répertoire « /home/subs/git/recalbox-build/buildroot »
Makefile:25 : la recette pour la cible « buildBR » a échouée
make: *** [buildBR] Erreur 2
```

Debug log file mentionned in the error :
```
0 info it worked if it ends with ok
1 verbose cli [ '/home/subs/git/recalbox-build/output/host/bin/node',
1 verbose cli   '/home/subs/git/recalbox-build/output/host/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.5.1
3 info using node@v8.9.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle client@0.1.0~prebuild: client@0.1.0
6 info lifecycle client@0.1.0~build: client@0.1.0
7 verbose lifecycle client@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle client@0.1.0~build: PATH: /home/subs/git/recalbox-build/output/host/lib/node_modules/npm/bin/node-gyp-bin:/home/subs/git/recalbox-build/output/build/recalbox-manager2-decb5ef4a4854a327059d0344cb9c98fceda2cd4/client/node_modules/.bin:/home/subs/git/recalbox-build/output/host/lib/node_modules/npm/bin/node-gyp-bin:/home/subs/git/recalbox-build/output/build/recalbox-manager2-decb5ef4a4854a327059d0344cb9c98fceda2cd4/node_modules/.bin:/home/subs/git/recalbox-build/output/host/bin:/home/subs/git/recalbox-build/output/host/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle client@0.1.0~build: CWD: /home/subs/git/recalbox-build/output/build/recalbox-manager2-decb5ef4a4854a327059d0344cb9c98fceda2cd4/client
10 silly lifecycle client@0.1.0~build: Args: [ '-c', 'react-scripts build' ]
11 silly lifecycle client@0.1.0~build: Returned: code: 1  signal: null
12 info lifecycle client@0.1.0~build: Failed to exec build script
13 verbose stack Error: client@0.1.0 build: `react-scripts build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/subs/git/recalbox-build/output/host/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/home/subs/git/recalbox-build/output/host/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid client@0.1.0
15 verbose cwd /home/subs/git/recalbox-build/output/build/recalbox-manager2-decb5ef4a4854a327059d0344cb9c98fceda2cd4/client
16 verbose Linux 4.4.0-104-generic
17 verbose argv "/home/subs/git/recalbox-build/output/host/bin/node" "/home/subs/git/recalbox-build/output/host/bin/npm" "run" "build"
18 verbose node v8.9.1
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error client@0.1.0 build: `react-scripts build`
22 error Exit status 1
23 error Failed at the client@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by substring** [comment]
The other debug log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/home/subs/git/recalbox-build/output/host/bin/node',
1 verbose cli   '/home/subs/git/recalbox-build/output/host/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.5.1
3 info using node@v8.9.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle client@0.1.0~prebuild: client@0.1.0
6 info lifecycle client@0.1.0~build: client@0.1.0
7 verbose lifecycle client@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle client@0.1.0~build: PATH: /home/subs/git/recalbox-build/output/host/lib/node_modules/npm/bin/node-gyp-bin:/home/subs/git/recalbox-build/output/build/recalbox-manager2-decb5ef4a4854a327059d0344cb9c98fceda2cd4/client/node_modules/.bin:/home/subs/git/recalbox-build/output/host/lib/node_modules/npm/bin/node-gyp-bin:/home/subs/git/recalbox-build/output/build/recalbox-manager2-decb5ef4a4854a327059d0344cb9c98fceda2cd4/node_modules/.bin:/home/subs/git/recalbox-build/output/host/bin:/home/subs/git/recalbox-build/output/host/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle client@0.1.0~build: CWD: /home/subs/git/recalbox-build/output/build/recalbox-manager2-decb5ef4a4854a327059d0344cb9c98fceda2cd4/client
10 silly lifecycle client@0.1.0~build: Args: [ '-c', 'react-scripts build' ]
11 silly lifecycle client@0.1.0~build: Returned: code: 1  signal: null
12 info lifecycle client@0.1.0~build: Failed to exec build script
13 verbose stack Error: client@0.1.0 build: `react-scripts build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/subs/git/recalbox-build/output/host/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/home/subs/git/recalbox-build/output/host/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid client@0.1.0
15 verbose cwd /home/subs/git/recalbox-build/output/build/recalbox-manager2-decb5ef4a4854a327059d0344cb9c98fceda2cd4/client
16 verbose Linux 4.4.0-104-generic
17 verbose argv "/home/subs/git/recalbox-build/output/host/bin/node" "/home/subs/git/recalbox-build/output/host/bin/npm" "run" "build"
18 verbose node v8.9.1
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error client@0.1.0 build: `react-scripts build`
22 error Exit status 1
23 error Failed at the client@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
